version: '3.8'

services:
  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - mf-shell
      - mf-characters
      - mf-character-detail
    networks:
      - mf-network
    restart: unless-stopped

  # MF-Shell (Main Application)
  mf-shell:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    networks:
      - mf-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # MF-Characters Microfrontend
  mf-characters:
    build:
      context: ./MF-Characters
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    networks:
      - mf-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # MF-CharacterDetail Microfrontend
  mf-character-detail:
    build:
      context: ./MF-CharacterDetail
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    networks:
      - mf-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  mf-network:
    driver: bridge

volumes:
  node_modules: 